#!/usr/bin/env sh
#
# SPDX-License-Identifier: BUSL-1.1
# Contributed by Algoritmic Lab Ltd. Copyright (C) 2024.
# Full license is available at https://github.com/stalwart-algoritmiclab/callisto-ui/tree/dev/LICENSES
#
. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged
